# Generated by Django 4.1.4 on 2023-03-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nested_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url_type',
            field=models.CharField(choices=[('url', 'URL'), ('named_url', 'Named URL')], default='url', max_length=20),
            preserve_default=False,
        ),
    ]
